kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: streamflow-ingress
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/target: infra-int
spec:
  entryPoints:
    - websecure
    - websecure-ext
  routes:
    - match: Host(`streamflow.sobrinho.pt`)
      kind: Rule
      services:
        - name: streamflow
          port: main
  tls:
    secretName: streamflow-cert
---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: streamflow-cert
  namespace: media
spec:
  secretName: streamflow-cert
  dnsNames:
    - streamflow.sobrinho.pt
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
