apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools

resources:
  - ../../base
  - cronjob.yaml
  - secrets/xfinity-usage-secret-enc.yaml
  - https://github.com/csobrinho/xfinity-usage//prometheus?ref=210baed9cc588038ef4cbcd42f5178ea8e62c0f5
