apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - cronjob-judy.yaml
  - cronjob-sobry.yaml
  - secrets/supermarket-secret-enc.yaml
  - secrets/supermarket-user-judy-secret-enc.yaml
  - secrets/supermarket-user-sobry-secret-enc.yaml
  - https://github.com/csobrinho/supermarket-api//prometheus?ref=7205249d1ee50e950859b1f61ba3eef966c769a7
