apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets/supermarket-secret-enc.yaml
  - https://github.com/csobrinho/supermarket-api//prometheus?ref=7205249d1ee50e950859b1f61ba3eef966c769a7

helmCharts:
  - name: supermarket
    releaseName: supermarket
    namespace: tools
    valuesInline:
      image: ghcr.io/csobrinho/supermarket-api:main@sha256:b1aaf1f8e4b9d37f2a5031656eac0378a2d7e773c7be53e8a926b0a83bc306dd
      users:
        - name: sobry
          schedule: "0 * * * *"
        - name: judy
          schedule: "2 * * * *"

helmGlobals:
  chartHome: helm
