apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcharr
  namespace: media
spec:
  selector:
    matchLabels:
      app: dispatcharr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dispatcharr
    spec:
      nodeSelector:
        kubernetes.io/arch: "amd64"
      containers:
        - name: dispatcharr
          image: ghcr.io/dispatcharr/dispatcharr:latest@sha256:0798b03927e12ceef4a154c0dd28e044a3ca5196ecbe76c41cb45ff65d9163ce
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c']
          args:
            - >
              sed -i 's/$$(CELERY_NICE_LEVEL)/5/g' /app/docker/uwsgi.ini; egrep
              '5|CELERY_NICE_LEVEL' /app/docker/uwsgi.ini;
              /app/docker/entrypoint.sh
          resources:
            limits:
              gpu.intel.com/i915: "1"
              cpu: 1000m
              memory: 2Gi
            requests:
              gpu.intel.com/i915: "1"
              cpu: 250m
              memory: 256Mi
          securityContext:
            privileged: true
          ports:
            - containerPort: 9191
          env:
            - name: TZ
              value: America/Los_Angeles
            - name: DISPATCHARR_LOG_LEVEL
              value: "info"
            - name: CELERY_NICE_LEVEL
              value: '5'
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /etc/profile.d
              name: profile
      securityContext:
        supplementalGroups:
          - 105 # Add render group.
          - 44
          - 107
          - 568
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dispatcharr-data
        - name: profile
          persistentVolumeClaim:
            claimName: dispatcharr-profile
