apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcharr
  namespace: media
spec:
  selector:
    matchLabels:
      app: dispatcharr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dispatcharr
    spec:
      nodeSelector:
        kubernetes.io/arch: "amd64"
      containers:
        - name: dispatcharr
          image: ghcr.io/dispatcharr/dispatcharr:latest@sha256:023af84fb2ccb64c19a189c9ab4a5b0da148f76e8c0823a959c5250ce2d480bf
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              gpu.intel.com/i915: "1"
              cpu: 1000m
              memory: 2Gi
            requests:
              gpu.intel.com/i915: "1"
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 9191
          env:
            - name: TZ
              value: America/Los_Angeles
            - name: DISPATCHARR_PORT
              value: $(DISPATCHARR_SERVICE_PORT)
          volumeMounts:
            - mountPath: /data
              name: data
      securityContext:
        supplementalGroups:
          - 105 # Add render group.
          - 44
          - 107
          - 568
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dispatcharr-data
