apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-auth-config
  namespace: media
data:
  config.toml: |
    [[roles]]
    name = "public"
    routes = ["GET /v1/portforward"]
    auth = "none"
