# From https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - bgp-config.yaml
  - kube-api-proxy.yaml
  - lb-pools.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    releaseName: cilium
    namespace: kube-system
    version: 1.18.5
    includeCRDs: true
    valuesFile: values.yaml
