# See https://github.com/kubernetes-csi/external-snapshotter/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - https://github.com/kubernetes-csi/external-snapshotter/client/config/crd/?ref=v8.5.0
  - https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/csi-snapshotter?ref=v8.5.0
  - https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller/?ref=v8.5.0
