# From https://github.com/trueforge-org/truecharts/blob/master/charts/library/common/values.yaml
# From https://github.com/trueforge-org/truecharts/blob/master/charts/stable/binner/values.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - deployment.yaml
  - ingress-route.yaml
  - pvc.yaml
  - service.yaml
